numpy
===

use lists to calculate:
$\vec{a}.\vec{b}$

In [131]:
import time

n = 100000000
a = [0.1 for i in range(n)]
b = [0.1 for i in range(n)]

c = 0

start = time.clock()

for i in range(n):
    c += a[i]*b[i]

end = time.clock()
speed_of_python = end-start
print(speed_of_python)

15.323200000000007


In [123]:
import numpy as np

arrays
-------

In [30]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

1D 2D and more

In [31]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

shape

In [69]:
a = np.array([1,2,3,4])
print(a.shape)
a = np.array([[1,2,1,1],[3,4,1,1],[5,6,1,1], [5,6,1,1]])
print(a.shape)
print(a.shape[0])

(4,)
(4, 4)
4


Indexing and slicing, : and ::, copy

In [70]:
print(a[1])
print(a[1,2])
print(a[:,1])
print(a[1,:])

a[:,1] = 0
print(a)
print(a[1:3,:])
a[::2,::2]=-1
print(a)
b = a.copy()
print(b)
b[:,:]=0
print(a)

[3 4 1 1]
1
[2 4 6 6]
[3 4 1 1]
[[1 0 1 1]
 [3 0 1 1]
 [5 0 1 1]
 [5 0 1 1]]
[[3 0 1 1]
 [5 0 1 1]]
[[-1  0 -1  1]
 [ 3  0  1  1]
 [-1  0 -1  1]
 [ 5  0  1  1]]
[[-1  0 -1  1]
 [ 3  0  1  1]
 [-1  0 -1  1]
 [ 5  0  1  1]]
[[-1  0 -1  1]
 [ 3  0  1  1]
 [-1  0 -1  1]
 [ 5  0  1  1]]


flatten, ravel, reshape

In [73]:
a.flatten()
a.ravel()

array([-1,  0, -1,  1,  3,  0,  1,  1, -1,  0, -1,  1,  5,  0,  1,  1])

In [89]:
a = np.array(range(24))
print(a)
a = a.reshape((3,4,2))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


 np.newaxis

In [90]:
a[:,:,:, np.newaxis].shape

(3, 4, 2, 1)

zeros, ones, zeros_like, ones_like

In [98]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.zeros_like(a))
print(np.ones_like(a))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]


In [102]:
a = np.ones(10)
b = np.ones(10)

In [103]:
a

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [105]:
a + b

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [106]:
a * b

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
3.0 * a 

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [132]:

a = np.ones(n)*0.1
b = np.ones(n)*0.1

start = time.clock()

np.dot(a,b)
end = time.clock()
speed_of_numpy = end-start
print(speed_of_numpy)

0.0984109999999987


In [134]:
speed_of_python/speed_of_numpy

155.70617105811556

In [137]:
a = np.ones((100,100))
b = np.ones((100,100))

a * b

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [138]:
a.dot(b)

array([[ 100.,  100.,  100., ...,  100.,  100.,  100.],
       [ 100.,  100.,  100., ...,  100.,  100.,  100.],
       [ 100.,  100.,  100., ...,  100.,  100.,  100.],
       ..., 
       [ 100.,  100.,  100., ...,  100.,  100.,  100.],
       [ 100.,  100.,  100., ...,  100.,  100.,  100.],
       [ 100.,  100.,  100., ...,  100.,  100.,  100.]])